import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/globals.css";
import { Header, Footer } from "@/components";

const madeTommy = localFont({
  src: [
    {
      path: "../public/fonts/MADETOMMY-Thin.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "../public/fonts/MADETOMMY-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/MADETOMMY.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/MADETOMMY-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/MADETOMMY-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/MADETOMMY-ExtraBold.woff2",
      weight: "800",
      style: "normal",
    },
    {
      path: "../public/fonts/MADETOMMY-Black.woff2",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-made-tommy",
  display: "swap",
});

const avenirNext = localFont({
  src: "../public/fonts/AvenirNextLTPro-Regular.woff2",
  variable: "--font-avenir-next",
  weight: "400",
  display: "swap",
});

const abygaer = localFont({
  src: "../public/fonts/Abygaer.woff2",
  variable: "--font-abygaer",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Vero Surfaces",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const links = [
    { label: "Portfolio", href: "#" },
    { label: "Materials", href: "#" },
    { label: "Services", href: "#" },
    { label: "Contact", href: "#" },
  ];

  return (
    <html lang="en">
      <body className={`${madeTommy.variable} ${avenirNext.variable} ${abygaer.variable} antialiased`}>
        <Header links={links} />
        {children}
        <Footer links={links} />
      </body>
    </html>
  );
}
